# =============================================================================
# Leaf — elasticsearch (coelhonexus standalone, 20-data layer)
# =============================================================================
# ECK Operator + ECK Stack (Elasticsearch 8.18 + Kibana). YCS uses this for:
#   - video metadata index (coelhonexus-youtube-metadata)
#   - transcript index (coelhonexus-youtube-transcriptions)
#
# Admin-only `elastic` password is auto-generated by ECK in Secret
# `elasticsearch-es-elastic-user` (key `elastic`). The app uses the
# deterministic demo user from env.hcl, constrained to Nexus YCS indexes.
#
# Adaptations vs COELHO Cloud's leaf:
#   - DROP dependency "tailscale_operator"
#   - DUMMY tailscale_domain + ingress_class (2 Ingresses inert in main.tf)
#   - minio creds via dependency
# =============================================================================

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  source = "${get_repo_root()}/infrastructure/modules/elasticsearch"
}

dependency "k3d" {
  config_path = "../../00-bootstrap/k3d"

  mock_outputs = {
    cluster_name    = "mock"
    kubeconfig_path = "/tmp/nonexistent-kubeconfig"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# Ordering-only.
dependencies {
  paths = ["../../10-platform/monitoring-crds"]
}

generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "kubernetes" {
      config_path = "${dependency.k3d.outputs.kubeconfig_path}"
    }
    provider "helm" {
      kubernetes = {
        config_path = "${dependency.k3d.outputs.kubeconfig_path}"
      }
    }
  EOF
}

inputs = {
  # Public-demo/local app credential. ECK still auto-generates the `elastic`
  # superuser password for admin jobs, but FastAPI/Celery should not use it.
  app_user_enabled = true
  app_username     = include.root.locals.env.demo.elasticsearch_username
  app_password     = include.root.locals.env.demo.elasticsearch_password
  # Shared app/chart code still authenticates as username `elastic`, so the
  # local cluster converges the built-in user's password to the deterministic
  # demo value below. This keeps plain `skaffold dev` working without touching
  # shared `apps/` or `k8s/`.
  elastic_password_override = include.root.locals.env.demo.elasticsearch_password

  # ECK auto-generates the `elastic` superuser password — no input needed.
  #
  # Defaults from variables.tf are appropriate:
  #   eck-operator 3.3.2, eck-stack 0.18.2, ES + Kibana 8.18.8, single node,
  #   200m/2Gi resources, 10Gi PVC, snapshots every 6h, retention 20.
}
