# =============================================================================
# Leaf — elasticsearch (coelhonexus standalone, 20-data layer)
# =============================================================================
# ECK Operator + ECK Stack (Elasticsearch 8.18 + Kibana). YCS uses this for:
#   - video metadata index (coelhonexus-youtube-metadata)
#   - transcript index (coelhonexus-youtube-transcriptions)
#
# Admin-only `elastic` password is auto-generated by ECK in Secret
# `elasticsearch-es-elastic-user` (key `elastic`). The app uses the
# deterministic demo user from env.hcl, constrained to Nexus YCS indexes.
#
# Adaptations vs COELHO Cloud's leaf:
#   - DROP the external-ingress-operator dependency
#   - DUMMY external-domain + ingress_class inputs (2 Ingresses inert in main.tf)
#   - minio creds via dependency
#   - Ported 2026-09-28: MinIO-backed snapshot backups. Cloud's main.tf
#     registers the MinIO bucket as an ES snapshot repo (via keystore
#     secureSettings, ES 8.18-compliant) and runs a CronJob against it;
#     Nexus's main.tf never wired this up even though the
#     k8s/backup-cronjob.yaml.tpl template already existed (dead code).
#     Added the `dependency "minio"` block below to match.
# =============================================================================

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  # `//elasticsearch` (not a trailing path) tells Terragrunt to copy the WHOLE
  # infrastructure/modules/ tree into its cache, then cd into elasticsearch/ —
  # needed because main.tf's `module "k3d_expose_es"` / `"k3d_expose_kibana"`
  # reference a SIBLING module via a relative path (same fix as neo4j/qdrant).
  source = "${get_repo_root()}/infrastructure/modules//elasticsearch"
}

dependency "k3d" {
  config_path = "../../00-bootstrap/k3d"

  mock_outputs = {
    cluster_name    = "mock"
    kubeconfig_path = "/tmp/nonexistent-kubeconfig"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# Snapshot backup CronJob target.
dependency "minio" {
  config_path = "../minio"

  mock_outputs = {
    api_endpoint = "http://minio.minio.svc.cluster.local:9000"
    access_key   = "mock"
    secret_key   = "mock"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# Ordering-only.
dependencies {
  paths = ["../../10-platform/monitoring-crds"]
}

generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "kubernetes" {
      config_path = "${dependency.k3d.outputs.kubeconfig_path}"
    }
    provider "helm" {
      kubernetes = {
        config_path = "${dependency.k3d.outputs.kubeconfig_path}"
      }
    }
  EOF
}

inputs = {
  # Public-demo/local app credential. ECK still auto-generates the `elastic`
  # superuser password for admin jobs, but FastAPI/Celery should not use it.
  app_user_enabled = true
  app_username     = include.root.locals.env.demo.elasticsearch_username
  app_password     = include.root.locals.env.demo.elasticsearch_password
  # Shared app/chart code still authenticates as username `elastic`, so the
  # local cluster converges the built-in user's password to the deterministic
  # demo value below. This keeps plain `skaffold dev` working without touching
  # shared `apps/` or `k8s/`.
  elastic_password_override = include.root.locals.env.demo.elasticsearch_password

  # ECK auto-generates the `elastic` superuser password — no input needed.

  # MinIO snapshot backup endpoint (ported from COELHO Cloud, 2026-09-28).
  minio_endpoint   = dependency.minio.outputs.api_endpoint
  minio_access_key = dependency.minio.outputs.access_key
  minio_secret_key = dependency.minio.outputs.secret_key

  # Defaults from variables.tf are appropriate:
  #   eck-operator 3.3.2, eck-stack 0.18.2, ES + Kibana 8.18.8, single node,
  #   200m/2Gi resources, 10Gi PVC, snapshots every 6h, retention 20.

  # Local access (k3d only) — ES 30477->23013, Kibana 30478->23014, mapped via
  # `k3d cluster edit coelhonexus --port-add "23013:30477@loadbalancer"`
  # `k3d cluster edit coelhonexus --port-add "23014:30478@loadbalancer"`
  # (run manually — not a Terraform resource, see infra/modules/k3d_expose).
  # Both are HTTPS with ECK's self-signed cert — browser will need a one-time
  # "accept the certificate" step, same as Rancher.
  enable_local_expose  = true
  k3d_es_node_port     = 30477
  k3d_kibana_node_port = 30478
}
