# =============================================================================
# neo4j module — inputs
# =============================================================================
# Chart: neo4j/neo4j v2026.3.1 (appVersion 2026.03.1, Community Edition).
# Repo: https://helm.neo4j.com/neo4j
#
# HTTPS-first exposure (the v2 fix for v1's HTTP-only LoadBalancer):
#   - Browser via external Ingress at https://neo4j.<domain> (port 7474)
#   - Bolt via external LoadBalancer at neo4j-bolt.<domain>:7687 with
#     Neo4j's native TLS (self-signed cert generated by Terraform)
#   - Browser URL: bolt+ssc://neo4j-bolt.<domain>:7687 (`+ssc` scheme accepts
#     the self-signed cert)
# =============================================================================

variable "chart_version" {
  description = "neo4j/neo4j Helm chart version. Latest: 2026.3.1 (appVersion 2026.03.1)."
  type        = string
  default     = "2026.3.1"

  validation {
    condition     = can(regex("^[0-9]+\\.[0-9]+\\.[0-9]+$", var.chart_version))
    error_message = "chart_version must be SemVer like '2026.3.1'."
  }
}

variable "namespace" {
  description = "Kubernetes namespace for Neo4j."
  type        = string
  default     = "neo4j"
}

variable "release_name" {
  description = "Helm release name. Used as Service prefix (chart creates `<release>` Service)."
  type        = string
  default     = "neo4j"
}

# -----------------------------------------------------------------------------
# Network exposure (external)
# -----------------------------------------------------------------------------

variable "tailscale_hostname_browser" {
  description = "External hostname for HTTPS Browser UI (e.g. 'neo4j' → neo4j.<domain>.example.com). External Ingress terminates TLS with an LE-issued cert."
  type        = string
  default     = "neo4j"
}

variable "tailscale_hostname_bolt" {
  description = "External hostname for the Bolt protocol (e.g. 'neo4j-bolt' → neo4j-bolt.<domain>.example.com). External LoadBalancer is TCP passthrough; Neo4j serves TLS natively."
  type        = string
  default     = "neo4j-bolt"
}

variable "tailscale_domain" {
  description = "External domain (e.g. 'YOUR_EXTERNAL_DOMAIN.example.com'). Comes from env.hcl. Still used for Neo4j's own advertised_address Helm values even though the external Ingress resources were removed — no operator on this cluster to fulfill them."
  type        = string
}

# -----------------------------------------------------------------------------
# Auth — password reused from v1 SOPS (per memory feedback_secrets_reuse)
# -----------------------------------------------------------------------------

variable "neo4j_password" {
  description = "Password for the built-in `neo4j` user. Reused from v1 — drop into SOPS as `neo4j.password` before applying."
  type        = string
  sensitive   = true
}

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------

variable "storage_size" {
  description = "Neo4j PVC size. v1 had 10Gi; trimmed to 5Gi for homelab. Bump if your graph grows past ~500k nodes."
  type        = string
  default     = "5Gi"
}

variable "storage_class" {
  description = "StorageClass for Neo4j PVC."
  type        = string
  default     = "local-path"
}

# -----------------------------------------------------------------------------
# Resource sizing
# -----------------------------------------------------------------------------
# Chart `_helpers.tpl:221` validator reads `.neo4j.resources.requests.memory`
# and enforces a 2 GiB MINIMUM on the REQUEST (not the limit). Burstable QoS
# (request < 2 GiB) is therefore impossible without forking the chart — so we
# stay Guaranteed (request == limit == 2Gi). All RAM savings come from JVM
# heap/pagecache/metaspace tuning (see heap_max_size + pagecache_size below).
#
# CPU: request must be >= 500m (same validator pattern, line 195). Limit can
# float higher for burst — 1000m allows the 6h apoc.export.cypher.all spike to
# burn a full core when it runs.

variable "cpu_request" {
  description = "CPU request for Neo4j container. Chart enforces minimum 500m."
  type        = string
  default     = "500m"
}

variable "cpu_limit" {
  description = "CPU limit for Neo4j container. Allows burst during 6h apoc.export.cypher.all backup."
  type        = string
  default     = "1000m"
}

variable "memory_request" {
  description = "Memory request. Chart-enforced floor is 2Gi (validator reads requests.memory). Cannot be lower."
  type        = string
  default     = "2Gi"
}

variable "memory_limit" {
  description = "Memory limit. Held at 2Gi to keep Guaranteed QoS; actual working-set is ~500 MiB."
  type        = string
  default     = "2Gi"
}

# -----------------------------------------------------------------------------
# JVM heap + page cache — tuned for a homelab knowledge graph (KB-scale data)
# -----------------------------------------------------------------------------

variable "heap_initial_size" {
  description = "Initial JVM heap (-Xms). Lazy-committed since AlwaysPreTouch is disabled. Restored 256m → 512m on 2026-06-07 to match the v1 cloud module that ran stable for months; the aggressive halving caused cold-pagecache→Metaspace pressure spirals when LangChain LLMGraphTransformer hit APOC."
  type        = string
  default     = "512m"
}

variable "heap_max_size" {
  description = "Max JVM heap (-Xmx). Restored 512m → 1G on 2026-06-07 (v1 default). Comfortably fits APOC + LangChain LLMGraphTransformer writes from COELHO Nexus YCS Phase 3."
  type        = string
  default     = "1G"
}

variable "pagecache_size" {
  description = "Neo4j page cache size. Restored 64m → 256m on 2026-06-07 (v1 default). The 64m floor was sized for KB-scale hot data only; the moment a multi-MB transcript landed via LangChain it forced disk reads that compounded Metaspace pressure into OOME crash loops."
  type        = string
  default     = "256m"
}

variable "tx_log_retention_policy" {
  description = "Transaction log retention. '3 files' caps tx logs at ~750 MiB; chart default '1 days' never rotates on quiet homelab."
  type        = string
  default     = "3 files"
}

# -----------------------------------------------------------------------------
# Feature toggles — disable subsystems we don't use to save RAM/CPU/logs
# -----------------------------------------------------------------------------

variable "enable_fleet_manager" {
  description = "Neo4j 2026.03's built-in Fleet Manager telemetry agent. Disabled by default — single-node homelab."
  type        = bool
  default     = false
}

variable "enable_usage_report" {
  description = "Anonymous usage data sent to Neo4j Inc."
  type        = bool
  default     = false
}

# Removed in 2026-05-25 Tier 1 fix: `server.metrics.enabled`,
# `dbms.security.log_successful_authentication`, `server.https.enabled`
# are Enterprise-only or don't exist in Neo4j 2026.03 CE. Setting them
# only emits "Unrecognized setting" WARNs at startup — see neo4j_optimization.md.

variable "http_allow_proxies" {
  description = "CIDR list of trusted upstream proxies for X-Forward headers. Default = RFC1918 (covers external ingress pod + cluster CIDRs without env-specific lookup)."
  type        = string
  default     = "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
}

variable "http_allow_hosts" {
  description = "Allowed Host headers from X-Forward. '*' is safe since the only public ingress is externally authenticated."
  type        = string
  default     = "*"
}

# -----------------------------------------------------------------------------
# v2 baseline MinIO — used ONLY by the backup CronJob
# -----------------------------------------------------------------------------

variable "minio_endpoint" {
  description = "MinIO S3 endpoint (in-cluster, with scheme)."
  type        = string
  default     = "http://minio.minio.svc.cluster.local:9000"
}

variable "minio_access_key" {
  description = "MinIO access key. Reused via the v2 MinIO module."
  type        = string
  sensitive   = true
}

variable "minio_secret_key" {
  description = "MinIO secret key."
  type        = string
  sensitive   = true
}

variable "backup_bucket" {
  description = "MinIO bucket for backup uploads. Uses the shared `backups` bucket with `neo4j/` prefix."
  type        = string
  default     = "backups"
}

variable "backup_schedule" {
  description = "Cron schedule for the backup CronJob."
  type        = string
  default     = "30 */6 * * *"
}

variable "backup_retention" {
  description = "Number of recent backups to keep in MinIO."
  type        = number
  default     = 20
}

# -----------------------------------------------------------------------------
# Local access (k3d dev clusters only — e.g. coelhonexus standalone)
# -----------------------------------------------------------------------------
# Opt-in NodePort Service so a human on their own laptop can open Neo4j
# Browser at localhost:<port> during development. Leave `enable_local_expose`
# unset (default false) on any environment where external Ingress already
# provides access — the module below is never even instantiated in that
# case. See infrastructure/modules/k3d_expose/.
#
# BOTH ports are required, not just HTTP: Neo4j Browser's JS loads over HTTP
# (7474) but opens a SEPARATE Bolt connection (7687) for the actual login —
# exposing only 7474 loads the page but fails at "Connect to instance" with
# a routing-discovery error.

variable "enable_local_expose" {
  description = "Create NodePort Services for localhost access via k3d's loadbalancer port mapping. Only meaningful on k3d-based dev clusters."
  type        = bool
  default     = false
}

variable "k3d_http_node_port" {
  description = "NodePort for local Neo4j Browser UI access (target port 7474). Required only when enable_local_expose = true; must be unique across the whole cluster."
  type        = number
  default     = null
}

variable "k3d_bolt_node_port" {
  description = "NodePort for local Bolt driver access (target port 7687) — needed for Browser's login step, and for any local Bolt client (cypher-shell, drivers). Required only when enable_local_expose = true; must be unique across the whole cluster."
  type        = number
  default     = null
}
