from __future__ import annotations


# =============================================================================
# MinIO object keys — same bucket as ingestion (coelhonexus); the `llm/` prefix
# namespaces rotator config away from `ingestion/` + `synth-vault/` corpora.
# =============================================================================
CREDENTIALS_KEY = "llm/credentials.enc"   # Fernet ciphertext of {key_env: api_key}
KEK_KEY         = "llm/kek.key"           # autogenerated Fernet KEK (when env unset)
SETTINGS_KEY    = "llm/settings.json"     # plaintext selection (non-secret)


# =============================================================================
# KEK (key-encryption-key) resolution
# =============================================================================
# Operator-provided Fernet key (urlsafe-b64, 32 bytes) — preferred: separates
# the unlock secret from the ciphertext (true at-rest separation). When unset,
# the store auto-generates one ONCE and persists it to MinIO `llm/kek.key`
# (zero-config, obfuscation-grade — KEK sits beside ciphertext but survives
# skaffold Ctrl+C/restart because the MinIO PVC is durable). Phase 4 wires the
# Helm chart to auto-generate + inject this env so deploys get real separation
# with no manual step. Either way the value is STABLE across restarts.
KEK_ENV = "KD_CREDS_KEY"


# =============================================================================
# Cache freshness
# =============================================================================
# In-process decrypted-key cache TTL. Short enough that a key set through the UI
# (FastAPI process) propagates to the Celery worker process within one TTL;
# long enough that one rotator build (~30 entry-builder reads) doesn't hammer
# MinIO. Same-process writes invalidate immediately (no TTL wait).
CACHE_TTL_S = 30.0


# =============================================================================
# Managed key_env allow-list — mirror of discovery/constants.py::PROVIDERS[*]
# .key_env. The store only ever reads/writes/masks these names so an arbitrary
# env var can't be exfiltrated through the settings API.
# =============================================================================
MANAGED_KEY_ENVS: tuple[str, ...] = (
    "GROQ_API_KEY",
    "NVIDIA_API_KEY",
    "CEREBRAS_API_KEY",
    "MISTRAL_API_KEY",
    "GOOGLE_API_KEY",
    "SAMBANOVA_API_KEY",
    "DEEPSEEK_API_KEY",
)
