"""Fernet-encrypted, MinIO-backed credential store + sync key resolution.

WHY SYNC: the rotator's provider entry-builders (`_groq_entry` etc. in
chain/service.py) are plain sync functions called while materializing the
LiteLLM Router. They can't `await`, so key resolution must be synchronous.
This module therefore talks to MinIO with a **sync botocore S3 client** (the
async `aioboto3` layer used elsewhere can't be awaited from sync code) and
keeps an in-process decrypted-key cache so a rotator build (~30 reads) costs at
most one MinIO GET per CACHE_TTL_S window.

THREAD SAFETY: a single `threading.RLock` guards the cache + KEK + S3 client.
Reads (resolve_key) and writes (set_key) are all serialized; the lock is held
only around in-memory state and short MinIO round-trips.

NEVER RAISES on the hot path: `resolve_key()` and the module-level
`resolve_key()` swallow every error and fall back to the env var, so a MinIO
outage / KEK mismatch degrades to "env-only" (today's behavior) instead of
breaking the rotator.

Layout in MinIO (bucket = MINIO_BUCKET_COELHONEXUS, default "coelhonexus"):
    llm/kek.key          autogenerated Fernet KEK (only when KD_CREDS_KEY unset)
    llm/credentials.enc  Fernet(json({key_env: api_key}))
    llm/settings.json    plaintext selection (enabled providers + models + mode)
"""
from __future__ import annotations

import copy
import json
import logging
import os
import threading
import time
from typing import Optional

from botocore.config import Config
from botocore.exceptions import ClientError
from botocore.session import get_session
from cryptography.fernet import Fernet, InvalidToken

from .constants import (
    CACHE_TTL_S,
    CREDENTIALS_KEY,
    KEK_ENV,
    KEK_KEY,
    MANAGED_KEY_ENVS,
    SETTINGS_KEY,
)


logger = logging.getLogger(__name__)


def _mask(key: str) -> Optional[str]:
    """Last-4 of a key for status display. Never expose more."""
    key = (key or "").strip()
    if not key:
        return None
    return key[-4:] if len(key) >= 4 else "*" * len(key)


class CredentialStore:
    """Sync, thread-safe, MinIO-backed encrypted provider-key store."""

    def __init__(self) -> None:
        self._lock = threading.RLock()
        # Decrypted {key_env: api_key}. Empty until first load.
        self._cache: dict[str, str] = {}
        self._loaded_at: float = 0.0
        self._cache_valid: bool = False
        self._kek_bytes: Optional[bytes] = None
        # Selection blob (llm/settings.json) cache. The rotator's selection
        # filter reads this on the hot path (per bandit call), so it's TTL-cached
        # like credentials instead of hitting MinIO every time.
        self._settings_cache: Optional[dict] = None
        self._settings_loaded_at: float = 0.0
        # MinIO connection params — mirror domains/dd/ingestion/storage.
        self._endpoint = os.environ.get("MINIO_ENDPOINT", "").strip()
        self._bucket = os.environ.get("MINIO_BUCKET_COELHONEXUS", "coelhonexus")
        self._access_key = os.environ.get("AWS_ACCESS_KEY_ID", "")
        self._secret_key = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
        self._boto_config = Config(
            signature_version="s3v4",
            connect_timeout=10,
            read_timeout=30,
            retries={"max_attempts": 5, "mode": "standard"},
        )

    # ------------------------------------------------------------------ S3 I/O
    def _client(self):
        if not self._endpoint:
            raise RuntimeError("MINIO_ENDPOINT unset — credential store unavailable")
        return get_session().create_client(
            "s3",
            endpoint_url=self._endpoint,
            aws_access_key_id=self._access_key,
            aws_secret_access_key=self._secret_key,
            region_name="us-east-1",
            config=self._boto_config,
        )

    def _get_object(self, key: str) -> Optional[bytes]:
        """Return object bytes, or None if it doesn't exist."""
        try:
            client = self._client()
            try:
                resp = client.get_object(Bucket=self._bucket, Key=key)
                return resp["Body"].read()
            finally:
                client.close()
        except ClientError as e:
            code = (e.response or {}).get("Error", {}).get("Code", "")
            if code in ("NoSuchKey", "404", "NoSuchBucket"):
                return None
            raise

    def _put_object(self, key: str, body: bytes, content_type: str) -> None:
        client = self._client()
        try:
            client.put_object(
                Bucket=self._bucket, Key=key, Body=body, ContentType=content_type,
            )
        finally:
            client.close()

    # ------------------------------------------------------------------ KEK
    def _kek(self) -> bytes:
        """Resolve the Fernet KEK (cached). env > MinIO-persisted-autogen."""
        if self._kek_bytes is not None:
            return self._kek_bytes
        env = os.environ.get(KEK_ENV, "").strip()
        if env:
            # Validate it's a usable Fernet key; raises on malformed input.
            Fernet(env.encode())
            self._kek_bytes = env.encode()
            logger.info("[llm-creds] KEK from %s env", KEK_ENV)
            return self._kek_bytes
        # Autogen-persist path. Re-GET after PUT so concurrent first-boot
        # processes converge on a single winner instead of diverging.
        existing = self._get_object(KEK_KEY)
        if existing and existing.strip():
            self._kek_bytes = existing.strip()
            return self._kek_bytes
        new = Fernet.generate_key()
        self._put_object(KEK_KEY, new, "application/octet-stream")
        confirmed = self._get_object(KEK_KEY)
        self._kek_bytes = (confirmed.strip() if confirmed else new)
        logger.info("[llm-creds] KEK auto-generated + persisted to %s", KEK_KEY)
        return self._kek_bytes

    def _legacy_autogen_kek(self) -> Optional[bytes]:
        """The MinIO-persisted autogen KEK, if present. Used to MIGRATE
        ciphertext when an env KEK (KD_CREDS_KEY) is newly introduced after keys
        were first stored under the autogen KEK — so enabling the Helm-managed
        KEK never silently orphans the user's saved keys."""
        try:
            existing = self._get_object(KEK_KEY)
            return existing.strip() if existing and existing.strip() else None
        except Exception:
            return None

    def _decrypt_credentials(self, raw: bytes) -> tuple[dict, bool]:
        """(mapping, used_legacy). Tries the primary KEK, then the MinIO
        autogen KEK as a one-way migration fallback. Raises InvalidToken if
        neither works."""
        primary = self._kek()
        try:
            return json.loads(Fernet(primary).decrypt(raw).decode("utf-8")), False
        except InvalidToken:
            legacy = self._legacy_autogen_kek()
            if legacy and legacy != primary:
                data = Fernet(legacy).decrypt(raw)   # may raise → genuine corruption
                return json.loads(data.decode("utf-8")), True
            raise

    # ------------------------------------------------------------------ cache
    def _reload_locked(self) -> None:
        """Decrypt credentials.enc into the cache. Caller holds the lock."""
        try:
            raw = self._get_object(CREDENTIALS_KEY)
            if not raw:
                self._cache = {}
            else:
                loaded, used_legacy = self._decrypt_credentials(raw)
                self._cache = {
                    str(k): str(v) for k, v in loaded.items() if v
                }
                if used_legacy:
                    # Re-encrypt under the (new) primary KEK so subsequent reads
                    # use it directly. Best-effort — a failure just means we
                    # migrate again next reload.
                    try:
                        self._persist_locked()
                        logger.info(
                            "[llm-creds] migrated credentials.enc to the "
                            "env KEK (KD_CREDS_KEY)"
                        )
                    except Exception as e:
                        logger.warning("[llm-creds] KEK migration re-encrypt failed: %s", e)
        except InvalidToken:
            logger.error(
                "[llm-creds] credentials.enc failed to decrypt (KEK changed or "
                "lost) — falling back to env keys only"
            )
            self._cache = {}
        except Exception as e:
            logger.warning(
                "[llm-creds] credential load failed (%s: %s) — env fallback",
                type(e).__name__, e,
            )
            # Keep any previously-loaded cache rather than wiping on a blip.
            if not self._cache_valid:
                self._cache = {}
        self._loaded_at = time.monotonic()
        self._cache_valid = True

    def _ensure_fresh(self) -> None:
        now = time.monotonic()
        with self._lock:
            if self._cache_valid and (now - self._loaded_at) < CACHE_TTL_S:
                return
            self._reload_locked()

    def _persist_locked(self) -> None:
        blob = Fernet(self._kek()).encrypt(
            json.dumps(self._cache, separators=(",", ":")).encode("utf-8")
        )
        self._put_object(CREDENTIALS_KEY, blob, "application/octet-stream")
        self._loaded_at = time.monotonic()
        self._cache_valid = True

    def _maybe_import_env_keys(self) -> int:
        """Opt-in (KD_CREDS_IMPORT_ENV=1) first-boot migration: copy provider
        keys present in the environment (Helm configmap) into the encrypted
        store, so the configmap entries can then be dropped. Only imports names
        not already stored. Returns the count imported."""
        flag = os.environ.get("KD_CREDS_IMPORT_ENV", "").strip().lower()
        if flag not in ("1", "true", "yes", "on"):
            return 0
        imported = 0
        with self._lock:
            self._reload_locked()
            changed = False
            for env_name in MANAGED_KEY_ENVS:
                if self._cache.get(env_name):
                    continue
                val = os.environ.get(env_name, "").strip()
                if val:
                    self._cache[env_name] = val
                    changed = True
                    imported += 1
            if changed:
                self._persist_locked()
        if imported:
            logger.info("[llm-creds] imported %d env key(s) into the store", imported)
        return imported

    # ------------------------------------------------------------------ public
    def warm(self) -> None:
        """Eagerly init the KEK + load the cache. Call once at process start
        (FastAPI lifespan / Celery worker init) so the first rotator build is
        served from cache. Best-effort: logs + returns on failure."""
        try:
            with self._lock:
                self._kek()
                self._reload_locked()
            self._maybe_import_env_keys()
            logger.info(
                "[llm-creds] warm: %d user key(s) loaded", len(self._cache)
            )
        except Exception as e:
            logger.warning(
                "[llm-creds] warm failed (%s: %s) — env fallback active",
                type(e).__name__, e,
            )

    def resolve_key(self, key_env: str) -> str:
        """User-store key if set, else env var. Never raises."""
        try:
            self._ensure_fresh()
            with self._lock:
                v = (self._cache.get(key_env) or "").strip()
            if v:
                return v
        except Exception as e:
            logger.debug("[llm-creds] resolve_key(%s) store miss: %s", key_env, e)
        return os.environ.get(key_env, "").strip()

    def set_key(self, key_env: str, api_key: str) -> dict:
        """Encrypt + store one provider key. Returns masked status."""
        if key_env not in MANAGED_KEY_ENVS:
            raise ValueError(f"unmanaged key_env: {key_env!r}")
        api_key = (api_key or "").strip()
        if not api_key:
            raise ValueError("empty api_key")
        with self._lock:
            self._reload_locked()          # latest before mutate (cross-process)
            self._cache[key_env] = api_key
            self._persist_locked()
        return self.key_status(key_env)

    def delete_key(self, key_env: str) -> dict:
        """Remove a user key → resolution reverts to the env fallback."""
        with self._lock:
            self._reload_locked()
            self._cache.pop(key_env, None)
            self._persist_locked()
        return self.key_status(key_env)

    def key_status(self, key_env: str) -> dict:
        """Masked status — has_key / source(user|env) / last4. No raw key."""
        self._ensure_fresh()
        with self._lock:
            stored = (self._cache.get(key_env) or "").strip()
        if stored:
            return {"has_key": True, "source": "user", "last4": _mask(stored)}
        env = os.environ.get(key_env, "").strip()
        if env:
            return {"has_key": True, "source": "env", "last4": _mask(env)}
        return {"has_key": False, "source": None, "last4": None}

    # ------------------------------------------------------------- selection
    def read_settings(self, force: bool = False) -> dict:
        """Plaintext non-secret selection blob. {} if never written.

        TTL-cached (CACHE_TTL_S) because the rotator's selection filter calls
        this on the hot path. A write through `write_settings` refreshes the
        cache immediately; other processes pick up changes within one TTL.
        `force=True` bypasses the cache (used by the dynamic-catalog rebuild so
        it always reflects the latest selection). Returns a copy so callers can
        mutate freely."""
        now = time.monotonic()
        if not force:
            with self._lock:
                if self._settings_cache is not None and \
                   (now - self._settings_loaded_at) < CACHE_TTL_S:
                    return copy.deepcopy(self._settings_cache)
        try:
            raw = self._get_object(SETTINGS_KEY)
            data = json.loads(raw.decode("utf-8")) if raw else {}
        except Exception as e:
            logger.warning("[llm-creds] settings read failed: %s", e)
            data = {}
        with self._lock:
            self._settings_cache = data
            self._settings_loaded_at = now
        return copy.deepcopy(data)

    def write_settings(self, settings: dict) -> None:
        self._put_object(
            SETTINGS_KEY,
            json.dumps(settings, separators=(",", ":")).encode("utf-8"),
            "application/json",
        )
        with self._lock:
            self._settings_cache = copy.deepcopy(settings)
            self._settings_loaded_at = time.monotonic()


# =============================================================================
# Module-level singleton + convenience
# =============================================================================
_store: Optional[CredentialStore] = None
_store_lock = threading.Lock()


def get_store() -> CredentialStore:
    global _store
    if _store is None:
        with _store_lock:
            if _store is None:
                _store = CredentialStore()
    return _store


def resolve_key(key_env: str) -> str:
    """Hot-path provider-key resolution: user-store key, else env. Never raises.

    This is the single function the rotator (chain + discovery) calls in place
    of `os.environ.get(key_env)`.
    """
    try:
        return get_store().resolve_key(key_env)
    except Exception:
        return os.environ.get(key_env, "").strip()


def warm() -> None:
    """Eager KEK init + cache load — call at process start."""
    try:
        get_store().warm()
    except Exception as e:
        logger.warning("[llm-creds] warm() failed: %s", e)
