apiVersion: v2
name: coelhonexus
description: coelhonexus
type: application
version: 1.0.0
appVersion: "1.0.0"


dependencies:
  - name: coelho-llm-rotator
    version: 1.1.7
    repository: oci://ghcr.io/rafaelcoelho1409/charts

