"""sawc — Pydantic schemas (v2 cookbook: Citation/Subtopic/Section + LLM
section draft + persisted ChapterDraft)."""
from __future__ import annotations

import re
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from .params import (
    CITATION_CLAIM_CHARS_MAX,
    CITATION_CLAIM_CHARS_MIN,
    CITATIONS_MAX,
    CITATIONS_MIN,
    EXPLANATION_WORDS_MAX,
    EXPLANATION_WORDS_MIN,
    HEADING_MAX_WORDS,
    HEADING_MIN_WORDS,
    INTRO_CHARS_MAX,
    INTRO_CHARS_MIN,
    MEMORY_SUMMARY_CHARS_MAX,
    MEMORY_SUMMARY_CHARS_MIN,
    MEMORY_TERM_CHARS_MAX,
    MEMORY_TERM_CHARS_MIN,
    MEMORY_TERMS_MAX,
    MEMORY_TERMS_MIN,
    N_DRAFTS,
    SUBHEADING_MAX_WORDS,
    SUBHEADING_MIN_WORDS,
    SUBTOPICS_MAX,
    SUBTOPICS_MIN,
)
from .patterns import HASH_RE
from .versions import SAWC_PROMPT_VERSION, SAWC_SCHEMA_VERSION


class Citation(BaseModel):
    """One citation: source the writer relied on, plus the specific claim
    it backs."""
    source_key: str = Field(
        description = (
            "MinIO source key (e.g. `ingestion/pydantic/pages/0024-isbn.md`)."
        ),
    )
    claim: str = Field(
        description = (
            "6-400 chars. The specific claim this source backs in the prose."
        ),
    )

    @field_validator("claim")
    @classmethod
    def _validate_claim(cls, v: str) -> str:
        s = " ".join(v.strip().split())
        if not (
            CITATION_CLAIM_CHARS_MIN <= len(s) <= CITATION_CLAIM_CHARS_MAX
        ):
            raise ValueError(
                f"citation.claim must be {CITATION_CLAIM_CHARS_MIN}-"
                f"{CITATION_CLAIM_CHARS_MAX} chars; got {len(s)}"
            )
        return s


class Subtopic(BaseModel):
    """One (subheading, explanation, code block) triple. Each Subtopic
    renders as a single H3 subsection in the final chapter."""
    code_ref_hash: str = Field(
        default = "",
        description = (
            "16-hex vault hash — PICK FIRST. MUST be in the section's "
            "allowed_hashes. PROSE PATH: leave EMPTY for a conceptual "
            "subtopic in a no-code section."
        ),
    )
    subheading: str = Field(
        description = (
            f"{SUBHEADING_MIN_WORDS}-{SUBHEADING_MAX_WORDS} words. H3 "
            f"naming what the chosen code block demonstrates."
        ),
    )
    explanation: str = Field(
        description = (
            f"{EXPLANATION_WORDS_MIN}-{EXPLANATION_WORDS_MAX} words. The "
            f"concise explanation that appears BEFORE the code block. "
            f"MUST reference at least one identifier visible in the "
            f"chosen code body."
        ),
    )
    code_source: Literal["verbatim", "derived"] = Field(
        default = "verbatim",
        description = (
            "Provenance tag. 'verbatim' = vault[hash] substituted; "
            "'derived' = AI-generated by sawc_derive."
        ),
    )
    derived_code: Optional[str] = Field(
        default = None,
        description = (
            "When code_source='derived', the AI-generated runnable code "
            "body. Required if 'derived'; MUST be None if 'verbatim'."
        ),
    )

    @field_validator("subheading")
    @classmethod
    def _validate_subheading(cls, v: str) -> str:
        s = v.strip()
        if s.lstrip().startswith("#"):
            raise ValueError("subheading must NOT start with '#'")
        words = s.split()
        if not (SUBHEADING_MIN_WORDS <= len(words) <= SUBHEADING_MAX_WORDS):
            raise ValueError(
                f"subheading must be {SUBHEADING_MIN_WORDS}-"
                f"{SUBHEADING_MAX_WORDS} words; got {len(words)} ({s!r})"
            )
        return s

    @field_validator("explanation")
    @classmethod
    def _validate_explanation(cls, v: str) -> str:
        s = " ".join(v.strip().split())
        words = s.split()
        if not (
            EXPLANATION_WORDS_MIN <= len(words) <= EXPLANATION_WORDS_MAX
        ):
            raise ValueError(
                f"explanation must be {EXPLANATION_WORDS_MIN}-"
                f"{EXPLANATION_WORDS_MAX} words; got {len(words)}"
            )
        if "```" in s or "<code-ref" in s or "<code id" in s:
            raise ValueError(
                "explanation must NOT contain code fences or inline "
                "code envelope tags — it's prose-only"
            )
        if re.search(r"(?m)^\s*#\s*docs?\s*:", s):
            raise ValueError(
                "explanation contains a `# docs:` source-id leak; use "
                "the `citations` field for source references."
            )
        return s

    @field_validator("code_ref_hash")
    @classmethod
    def _validate_hash(cls, v: str) -> str:
        if v and not HASH_RE.match(v):
            raise ValueError(
                f"code_ref_hash {v!r} must be 16 lowercase hex chars "
                f"(or empty \"\" for a prose subtopic)"
            )
        return v

    @field_validator("derived_code")
    @classmethod
    def _validate_derived_code(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        s = v.rstrip()
        if not s.strip():
            raise ValueError("derived_code, when set, must be non-empty")
        if len(s) > 8000:
            raise ValueError(
                f"derived_code too long ({len(s)} chars; max 8000)"
            )
        return s

    @model_validator(mode = "after")
    def _validate_source_code_pair(self) -> "Subtopic":
        if self.code_source == "derived":
            if not self.derived_code:
                raise ValueError(
                    "code_source='derived' requires non-empty derived_code"
                )
        else:  # verbatim
            if self.derived_code is not None:
                raise ValueError(
                    "code_source='verbatim' must NOT set derived_code"
                )
        return self


class LLMSectionDraft(BaseModel):
    """Cookbook-style section schema (v2). The LLM emits a sequence of
    Subtopic triples."""
    heading: str = Field(
        description = (
            f"{HEADING_MIN_WORDS}-{HEADING_MAX_WORDS} words. ECHO the "
            f"outline H2 heading verbatim."
        ),
    )
    intro: str = Field(
        description = (
            f"{INTRO_CHARS_MIN}-{INTRO_CHARS_MAX} chars. 1-2 sentences "
            f"framing the H2 section."
        ),
    )
    subtopics: list[Subtopic] = Field(
        description = (
            f"{SUBTOPICS_MIN}-{SUBTOPICS_MAX} Subtopic triples."
        ),
    )
    citations: list[Citation] = Field(
        default_factory = list,
        description = (
            f"{CITATIONS_MIN}-{CITATIONS_MAX} citations."
        ),
    )

    @field_validator("heading")
    @classmethod
    def _validate_heading(cls, v: str) -> str:
        words = v.strip().split()
        if not (HEADING_MIN_WORDS <= len(words) <= HEADING_MAX_WORDS):
            raise ValueError(
                f"heading must be {HEADING_MIN_WORDS}-{HEADING_MAX_WORDS} "
                f"words; got {len(words)} ({v!r})"
            )
        if v.lstrip().startswith("#"):
            raise ValueError("heading must NOT start with '#'")
        return v.strip()

    @field_validator("intro")
    @classmethod
    def _validate_intro(cls, v: str) -> str:
        s = " ".join(v.strip().split())
        if not (INTRO_CHARS_MIN <= len(s) <= INTRO_CHARS_MAX):
            raise ValueError(
                f"intro must be {INTRO_CHARS_MIN}-{INTRO_CHARS_MAX} "
                f"chars; got {len(s)}"
            )
        if "```" in s or "<code-ref" in s or "<code id" in s:
            raise ValueError(
                "intro must NOT contain code blocks/envelopes — pure prose"
            )
        return s

    @field_validator("subtopics")
    @classmethod
    def _validate_subtopics(cls, v: list[Subtopic]) -> list[Subtopic]:
        if not (SUBTOPICS_MIN <= len(v) <= SUBTOPICS_MAX):
            raise ValueError(
                f"subtopics count must be {SUBTOPICS_MIN}-{SUBTOPICS_MAX}; "
                f"got {len(v)}"
            )
        hashes = [s.code_ref_hash for s in v if s.code_ref_hash]
        if len(set(hashes)) != len(hashes):
            raise ValueError(
                f"duplicate code_ref_hash across subtopics: {hashes}"
            )
        subheads = [s.subheading.casefold() for s in v]
        if len(set(subheads)) != len(subheads):
            raise ValueError(
                f"duplicate subheading across subtopics: "
                f"{[s.subheading for s in v]}"
            )
        return v

    @field_validator("citations")
    @classmethod
    def _validate_citations(cls, v: list[Citation]) -> list[Citation]:
        if not (CITATIONS_MIN <= len(v) <= CITATIONS_MAX):
            raise ValueError(
                f"citations count must be {CITATIONS_MIN}-{CITATIONS_MAX}; "
                f"got {len(v)}"
            )
        return v


class Section(BaseModel):
    """Persisted section (v2 cookbook). LLM fields + node-injected
    observability/meta."""
    section_id:        str
    heading:           str
    intro:             str
    subtopics:         list[Subtopic]
    citations:         list[Citation]
    wall_ms:           Optional[int] = None
    deployment_writer: Optional[str] = None
    deployment_critic: Optional[str] = None
    n_drafts_tried:    int = N_DRAFTS
    n_repairs:         int = 0
    chosen_draft_idx:  Optional[int] = None
    structural_score:  Optional[float] = None
    fallback_picker:   Optional[
        Literal["self_certainty", "structural_score"]
    ] = None
    issues:            list[str] = Field(default_factory = list)


class MemoryEntry(BaseModel):
    """One row of the SAWC memory ledger ℳ."""
    section_id:       str
    heading:          str
    summary:          str             # 40-600 chars
    key_terminology:  list[str]       # 0-12 entries, each 2-80 chars

    @field_validator("summary")
    @classmethod
    def _validate_summary(cls, v: str) -> str:
        s = " ".join(v.strip().split())
        if not (
            MEMORY_SUMMARY_CHARS_MIN <= len(s) <= MEMORY_SUMMARY_CHARS_MAX
        ):
            raise ValueError(
                f"memory summary must be {MEMORY_SUMMARY_CHARS_MIN}-"
                f"{MEMORY_SUMMARY_CHARS_MAX} chars; got {len(s)}"
            )
        return s

    @field_validator("key_terminology")
    @classmethod
    def _validate_terms(cls, v: list[str]) -> list[str]:
        if not (MEMORY_TERMS_MIN <= len(v) <= MEMORY_TERMS_MAX):
            raise ValueError(
                f"key_terminology count must be {MEMORY_TERMS_MIN}-"
                f"{MEMORY_TERMS_MAX}; got {len(v)}"
            )
        cleaned: list[str] = []
        for t in v:
            s = " ".join(t.strip().split())
            if not (MEMORY_TERM_CHARS_MIN <= len(s) <= MEMORY_TERM_CHARS_MAX):
                raise ValueError(
                    f"term length must be {MEMORY_TERM_CHARS_MIN}-"
                    f"{MEMORY_TERM_CHARS_MAX} chars; got {len(s)} ({t!r})"
                )
            cleaned.append(s)
        seen: set[str] = set()
        out: list[str] = []
        for t in cleaned:
            key = t.casefold()
            if key in seen:
                continue
            seen.add(key)
            out.append(t)
        return out


class SAWCStats(BaseModel):
    """Aggregate observability stats over the chapter draft."""
    n_sections:           int
    n_sections_completed: int
    n_sections_fallback:  int
    n_stages:             int
    n_total_drafts_fired: int
    n_critic_picks:       int
    n_picker_fallbacks:   int
    n_repairs:            int
    total_subtopics:      int
    total_citations:      int
    avg_subtopics_per_section: float
    avg_explanation_words: float


class ChapterDraft(BaseModel):
    """Full chapter draft — what gets persisted to MinIO as
    sawc-latest.json."""
    schema_version: str = SAWC_SCHEMA_VERSION
    prompt_version: str = SAWC_PROMPT_VERSION
    chapter_id:     str
    chapter_title:  str
    framework_slug: str
    sections:       list[Section]
    memory_final:   list[MemoryEntry]
    coverage_stats: SAWCStats
