# =============================================================================
# Leaf unit — monitoring CRDs (Prometheus Operator CRDs, homelab env, 10-platform layer)
# =============================================================================
#
# This is the FIRST leaf with `dependency` and `generate` blocks — the two
# Terragrunt features that make multi-unit deployments work.
#
# Apply with:
#   cd ~/COELHOCloud/infrastructure/live/homelab/10-platform/monitoring-crds
#   terragrunt init
#   terragrunt plan
#   terragrunt apply
#
# State written to:
#   http://localhost:9000/tfstate/homelab/10-platform/monitoring-crds/terraform.tfstate
# =============================================================================

# ---------------------------------------------------------------------------
# Inherit backend + env-level inputs from root.hcl (which reads env.hcl).
# ---------------------------------------------------------------------------
include "root" {
  path = find_in_parent_folders("root.hcl")
}

# ---------------------------------------------------------------------------
# Point at the recipe (pure-TF module).
# ---------------------------------------------------------------------------
terraform {
  source = "${get_repo_root()}/infrastructure/modules/monitoring-crds"
}

# ---------------------------------------------------------------------------
# DEPENDENCY block — first time we use this.
# ---------------------------------------------------------------------------
# Reads another unit's outputs (from its remote state in MinIO) and exposes
# them under `dependency.<name>.outputs.<key>` for use below.
#
# Resolution:
#   1. Terragrunt reads tfstate/homelab/00-bootstrap/k3d/terraform.tfstate
#   2. Extracts the `outputs` map from that state
#   3. Makes it available as dependency.k3d.outputs.kubeconfig_path, etc.
#
# `mock_outputs`: fake values used when the upstream state doesn't exist yet.
#   Useful for `terragrunt plan` in CI/review BEFORE the upstream has been
#   applied. Without these, `plan` would error trying to read missing state.
#
# `mock_outputs_allowed_terraform_commands`: whitelist of commands that may
#   USE the mocks. `apply` is deliberately NOT in this list — applying with
#   fake values would mean trying to install Helm onto a nonexistent cluster.
#   So `terragrunt apply` errors if k3d's state is missing (correct).
# ---------------------------------------------------------------------------
dependency "k3d" {
  config_path = "../../00-bootstrap/k3d"

  mock_outputs = {
    cluster_name    = "mock"
    kubeconfig_path = "/tmp/nonexistent-kubeconfig"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# ---------------------------------------------------------------------------
# GENERATE block — first time we use this.
# ---------------------------------------------------------------------------
# Terragrunt writes the contents below into the file `providers.tf` inside
# this unit's `.terragrunt-cache/<hash>/<src>/` directory, BEFORE calling
# `tofu init`. The module itself has NO `provider {}` blocks (pure module
# discipline) — we inject the configured provider per-leaf here.
#
# `if_exists = "overwrite_terragrunt"`: only overwrite files that Terragrunt
#   created. Doesn't touch hand-written .tf files in the module source.
#
# Why per-unit (not in root.hcl)?
#   The k3d unit itself doesn't have a cluster yet (it CREATES one). If we put
#   `provider "helm" {}` in root, every unit would inherit it — including k3d
#   — and k3d would fail at init trying to connect to a kubeconfig that
#   doesn't exist. Each unit declares only the providers it actually needs,
#   configured against THIS unit's specific upstream dependencies.
# ---------------------------------------------------------------------------
generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Auto-generated by Terragrunt. Do not edit.
    # Provider points at the cluster created by the upstream k3d unit.
    provider "helm" {
      kubernetes = {
        config_path = "${dependency.k3d.outputs.kubeconfig_path}"
      }
    }
  EOF
}

# ---------------------------------------------------------------------------
# Inputs — merged with what root.hcl provides.
# ---------------------------------------------------------------------------
# Module defaults:
#   chart_version = "28.0.1"
#   namespace     = "monitoring"
#   helm_timeout  = 120
#
# We could omit `inputs = {}` entirely and rely on defaults, but listing them
# explicitly here serves as a "this is what we deployed" record close to the
# leaf code.
# ---------------------------------------------------------------------------
inputs = {
  chart_version = "28.0.1"
  namespace     = "monitoring"
  helm_timeout  = 120
}
