"""
YouTube Transcript Extraction via Playwright CDP (Optimized v2)

Optimizations applied:
- Aggressive resource blocking (video, ads, tracking)
- Kill YouTube background processes immediately
- JS execution instead of Playwright clicks (faster)
- Event-based waiting (no arbitrary timeouts)
- Manual transcript priority over auto-generated

Usage:
    python -m scripts.youtube_transcript dQw4w9WgXcQ
    python -m scripts.youtube_transcript dQw4w9WgXcQ --headed
"""

import asyncio
import json
import os
import re
import ssl
import time
from dataclasses import dataclass
from typing import Optional
from urllib.parse import urlparse
from urllib.request import urlopen

from playwright.async_api import async_playwright, Page


# CDP endpoints (Tailscale addresses)
CDP_HEADLESS = os.getenv("PLAYWRIGHT_CDP_HEADLESS", "https://playwright-cdp-headless.YOUR_TAILNET_DOMAIN.ts.net")
CDP_HEADED = os.getenv("PLAYWRIGHT_CDP_HEADED", "https://playwright-cdp.YOUR_TAILNET_DOMAIN.ts.net")

# Resource blocking patterns - balanced for speed and reliability
BLOCK_PATTERNS = [
    # === VIDEO/AUDIO STREAMING (Biggest speedup: 2-5 seconds) ===
    "**/videoplayback*",
    "**/googlevideo.com/*",
    "**/*.googlevideo.com/*",
    # === ADS ===
    "**/doubleclick.net/*",
    "**/googleadservices.com/*",
    "**/googlesyndication.com/*",
    "**/googleads.g.doubleclick.net/*",
    "**/youtube.com/pagead/*",
    # === ANALYTICS/TRACKING ===
    "**/google-analytics.com/*",
    "**/googletagmanager.com/*",
    "**/youtube.com/api/stats/*",
    "**/youtube.com/ptracking*",
    "**/s.youtube.com/*",
]
# NOTE: Blocking images breaks some video pages - don't block them

BLOCK_RESOURCE_TYPES = {"media"}  # Only block media (video/audio)


@dataclass
class TranscriptSegment:
    timestamp: str
    text: str


@dataclass
class CaptionTrack:
    language_code: str
    name: str
    is_auto_generated: bool
    base_url: str


@dataclass
class TranscriptResult:
    video_id: str
    segments: list[TranscriptSegment]
    language: str
    is_auto_generated: bool
    method: str
    raw_text: str


def get_cdp_websocket_url(cdp_endpoint: str) -> str:
    """Get proper WebSocket URL for CDP connection via HTTPS proxy."""
    parsed = urlparse(cdp_endpoint)
    json_url = f"{cdp_endpoint}/json/version"

    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        with urlopen(json_url, timeout=10, context=ctx) as response:
            data = json.loads(response.read().decode())
            ws_url = data.get("webSocketDebuggerUrl", "")

            if not ws_url:
                return cdp_endpoint

            ws_parsed = urlparse(ws_url)
            ws_path = ws_parsed.path

            if parsed.scheme == "https":
                return f"wss://{parsed.netloc}{ws_path}"
            return f"ws://{parsed.netloc}{ws_path}"

    except Exception as e:
        print(f"[cdp] Failed to fetch {json_url}: {e}")
        return cdp_endpoint


async def setup_routes(page: Page) -> None:
    """Set up aggressive resource blocking."""
    for pattern in BLOCK_PATTERNS:
        await page.route(pattern, lambda r: r.abort())

    async def block_by_type(route):
        if route.request.resource_type in BLOCK_RESOURCE_TYPES:
            await route.abort()
        else:
            await route.continue_()

    await page.route("**/*", block_by_type)


async def kill_youtube_background(page: Page) -> None:
    """Kill YouTube's resource-hungry background processes."""
    await page.evaluate('''
        () => {
            // Kill video element
            const video = document.querySelector("video");
            if (video) {
                video.pause();
                video.removeAttribute("src");
                video.load();
            }
            // Clear intervals/timeouts
            const highestId = window.setTimeout(() => {}, 0);
            for (let i = 0; i < highestId; i++) {
                window.clearTimeout(i);
                window.clearInterval(i);
            }
        }
    ''')


async def get_caption_tracks(page: Page) -> list[CaptionTrack]:
    """Extract caption tracks from ytInitialPlayerResponse."""
    tracks_data = await page.evaluate('''
        () => {
            const caps = window.ytInitialPlayerResponse?.captions;
            if (!caps?.playerCaptionsTracklistRenderer?.captionTracks) return [];
            return caps.playerCaptionsTracklistRenderer.captionTracks.map(t => ({
                languageCode: t.languageCode || '',
                name: t.name?.simpleText || t.languageCode || '',
                isAutoGenerated: t.kind === 'asr' || (t.vssId || '').startsWith('a.'),
                baseUrl: t.baseUrl || ''
            }));
        }
    ''')

    return [
        CaptionTrack(
            language_code=t['languageCode'],
            name=t['name'],
            is_auto_generated=t['isAutoGenerated'],
            base_url=t['baseUrl']
        )
        for t in tracks_data
    ]


async def fetch_transcript_direct(page: Page, base_url: str) -> list[dict]:
    """Try to fetch transcript directly from caption URL."""
    json_url = base_url + ("&" if "?" in base_url else "?") + "fmt=json3"

    result = await page.evaluate(f'''
        async () => {{
            try {{
                const resp = await fetch("{json_url}", {{
                    credentials: "include",
                    headers: {{ "Accept": "application/json" }}
                }});
                const text = await resp.text();
                if (text.startsWith('<')) return {{ error: "blocked" }};
                return JSON.parse(text);
            }} catch (e) {{
                return {{ error: e.message }};
            }}
        }}
    ''')

    if 'error' in result:
        raise ValueError(result['error'])

    segments = []
    for event in result.get('events', []):
        if 'segs' in event:
            text = ''.join(s.get('utf8', '') for s in event['segs']).strip()
            if text:
                start_ms = event.get('tStartMs', 0)
                minutes = start_ms // 60000
                seconds = (start_ms // 1000) % 60
                segments.append({'timestamp': f"{minutes}:{seconds:02d}", 'text': text})

    return segments


async def extract_via_dom(page: Page, timeout_ms: int) -> str:
    """Extract transcript via DOM interaction (fallback)."""
    # Wait for page content to fully initialize
    try:
        await page.wait_for_selector('ytd-watch-metadata, #above-the-fold', timeout=15000)
    except Exception as e:
        print(f"[dom] Metadata selector not found: {e}")

    # Additional wait for dynamic content
    await page.wait_for_timeout(2000)

    # Check if page loaded properly
    page_check = await page.evaluate('''
        () => ({
            hasVideo: !!document.querySelector('video'),
            hasTitle: !!document.querySelector('h1.ytd-watch-metadata'),
            bodyLength: document.body.innerText.length,
            hasConsent: !!document.querySelector('ytd-consent-bump-v2-lightbox'),
        })
    ''')
    print(f"[dom] Page check: {page_check}")

    # Handle consent dialog if present
    if page_check.get('hasConsent'):
        print("[dom] Consent dialog detected, attempting to accept...")
        try:
            accept_btn = page.locator('button[aria-label*="Accept"], button:has-text("Accept all")').first
            if await accept_btn.count() > 0:
                await accept_btn.click(timeout=3000)
                await page.wait_for_timeout(2000)
        except:
            pass

    # First check if transcript panel is already visible
    already_visible = await page.evaluate('''
        () => {
            const panels = document.querySelectorAll('ytd-engagement-panel-section-list-renderer');
            for (const p of panels) {
                if (p.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
                    && /\\d+:\\d{2}/.test(p.innerText)) {
                    return true;
                }
            }
            return false;
        }
    ''')

    if already_visible:
        print("[dom] Transcript panel already visible")
        return await page.evaluate('''
            () => {
                const panels = document.querySelectorAll('ytd-engagement-panel-section-list-renderer');
                for (const p of panels) {
                    if (p.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
                        && /\\d+:\\d{2}/.test(p.innerText)) {
                        return p.innerText;
                    }
                }
                return '';
            }
        ''')

    # Method 1: Try expand button
    expanded = False
    try:
        expand_btn = page.locator("tp-yt-paper-button#expand:not([hidden])").first
        if await expand_btn.count() > 0:
            await expand_btn.click(timeout=2000)
            await page.wait_for_timeout(500)
            expanded = True
    except:
        pass

    # Method 2: Try clicking on description to expand
    if not expanded:
        try:
            desc = page.locator("#description-inline-expander, ytd-text-inline-expander").first
            if await desc.count() > 0:
                await desc.click(timeout=2000)
                await page.wait_for_timeout(500)
        except:
            pass

    # Method 3: Try "Show transcript" button
    transcript_selectors = [
        'button[aria-label="Show transcript"]',
        'ytd-video-description-transcript-section-renderer button',
    ]

    clicked = False
    for selector in transcript_selectors:
        try:
            btn = page.locator(selector).first
            if await btn.count() > 0:
                await btn.click(timeout=2000)
                clicked = True
                break
        except:
            continue

    # Method 4: Try "More actions" menu
    if not clicked:
        try:
            more_btn = page.locator('button[aria-label="More actions"]').first
            if await more_btn.count() > 0:
                await more_btn.click(timeout=2000)
                await page.wait_for_timeout(300)
                menu_item = page.locator('tp-yt-paper-listbox ytd-menu-service-item-renderer').filter(has_text="transcript")
                if await menu_item.count() > 0:
                    await menu_item.first.click(timeout=2000)
                    clicked = True
        except:
            pass

    if not clicked:
        debug = await page.evaluate('''
            () => ({
                url: window.location.href,
                title: document.title,
                expandBtns: document.querySelectorAll('tp-yt-paper-button#expand').length,
                moreActionsBtns: document.querySelectorAll('button[aria-label="More actions"]').length,
                descSection: !!document.querySelector('ytd-video-description-transcript-section-renderer'),
                allAriaLabels: Array.from(document.querySelectorAll('button[aria-label]'))
                    .map(b => b.getAttribute('aria-label'))
                    .filter(l => l && (l.toLowerCase().includes('transcript') || l.toLowerCase().includes('more')))
            })
        ''')
        print(f"[debug] {debug}")
        raise ValueError("Transcript button not found")

    # Wait for transcript panel with timestamps
    await page.wait_for_function(
        '''() => {
            const panels = document.querySelectorAll('ytd-engagement-panel-section-list-renderer');
            for (const p of panels) {
                if (p.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
                    && /\\d+:\\d{2}/.test(p.innerText)) {
                    return true;
                }
            }
            return false;
        }''',
        timeout=timeout_ms,
    )

    # Extract text
    return await page.evaluate('''
        () => {
            const panels = document.querySelectorAll('ytd-engagement-panel-section-list-renderer');
            for (const p of panels) {
                if (p.getAttribute('visibility') === 'ENGAGEMENT_PANEL_VISIBILITY_EXPANDED'
                    && /\\d+:\\d{2}/.test(p.innerText)) {
                    return p.innerText;
                }
            }
            return '';
        }
    ''')


def parse_transcript_text(raw_text: str) -> list[TranscriptSegment]:
    """Parse raw transcript text into segments."""
    lines = [line.strip() for line in raw_text.split("\n") if line.strip()]
    segments = []

    i = 0
    while i < len(lines) and not re.match(r"^\d+:\d{2}$", lines[i]):
        i += 1

    while i < len(lines):
        line = lines[i]
        if re.match(r"^\d+:\d{2}$", line):
            timestamp = line
            i += 1
            if i < len(lines) and re.match(r"^\d+\s+(second|minute)", lines[i]):
                i += 1
            text_parts = []
            while i < len(lines) and not re.match(r"^\d+:\d{2}$", lines[i]):
                text_parts.append(lines[i])
                i += 1
            if text_parts:
                segments.append(TranscriptSegment(timestamp=timestamp, text=" ".join(text_parts)))
        else:
            i += 1

    return segments


def select_best_track(tracks: list[CaptionTrack], prefer_manual: bool = True) -> CaptionTrack:
    """Select best track: English manual > any manual > English auto > any."""
    def priority(t: CaptionTrack) -> tuple:
        is_english = t.language_code.startswith('en')
        is_portuguese = t.language_code.startswith('pt')
        return (
            t.is_auto_generated if prefer_manual else False,
            0 if is_english else (1 if is_portuguese else 2),
        )

    return sorted(tracks, key=priority)[0]


async def extract_transcript(
    video_id: str,
    headless: bool = True,
    cdp_url: Optional[str] = None,
    timeout_ms: int = 12000,
    prefer_manual: bool = True,
) -> TranscriptResult:
    """Extract transcript from YouTube video (optimized)."""
    if cdp_url is None:
        cdp_endpoint = CDP_HEADLESS if headless else CDP_HEADED
        cdp_url = get_cdp_websocket_url(cdp_endpoint)

    print(f"[cdp] {cdp_url[:60]}...")

    url = f"https://www.youtube.com/watch?v={video_id}"

    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp(cdp_url)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 720},
        )
        page = await context.new_page()

        # Set up blocking BEFORE navigation
        await setup_routes(page)

        # Navigation - use 'load' to ensure page is fully ready
        await page.goto(url, wait_until="load")

        # Kill background processes immediately
        await kill_youtube_background(page)

        # Wait for captions data (usually instant)
        try:
            await page.wait_for_function(
                '() => !!window.ytInitialPlayerResponse?.captions',
                timeout=5000
            )
        except:
            pass

        # Get caption tracks
        tracks = await get_caption_tracks(page)

        if tracks:
            manual_count = sum(1 for t in tracks if not t.is_auto_generated)
            print(f"[tracks] {len(tracks)} found ({manual_count} manual)")

            selected = select_best_track(tracks, prefer_manual)
            print(f"[selected] {selected.language_code} ({'auto' if selected.is_auto_generated else 'manual'})")

            # Try direct API first
            try:
                segments_data = await fetch_transcript_direct(page, selected.base_url)
                await context.close()

                segments = [TranscriptSegment(timestamp=s['timestamp'], text=s['text']) for s in segments_data]
                raw_text = "\n".join(f"[{s.timestamp}] {s.text}" for s in segments)

                return TranscriptResult(
                    video_id=video_id,
                    segments=segments,
                    language=selected.language_code,
                    is_auto_generated=selected.is_auto_generated,
                    method="direct_api",
                    raw_text=raw_text,
                )
            except Exception as e:
                print(f"[direct] Failed: {e}")

        # Fallback to DOM scraping
        raw_text = await extract_via_dom(page, timeout_ms)
        await context.close()

        if not raw_text:
            raise ValueError(f"No transcript for: {video_id}")

        segments = parse_transcript_text(raw_text)
        is_auto = "auto-generated" in raw_text.lower()
        lang = tracks[0].language_code if tracks else "auto"

        return TranscriptResult(
            video_id=video_id,
            segments=segments,
            language=lang,
            is_auto_generated=is_auto,
            method="dom_scrape",
            raw_text=raw_text,
        )


async def main():
    import argparse

    parser = argparse.ArgumentParser(description="YouTube transcript extraction (optimized)")
    parser.add_argument("video_id", help="YouTube video ID")
    parser.add_argument("--headed", action="store_true", help="Use headed browser")
    parser.add_argument("--cdp-url", help="Custom CDP endpoint")
    args = parser.parse_args()

    print(f"\nExtracting: {args.video_id} ({'headed' if args.headed else 'headless'})\n")

    t0 = time.time()
    result = await extract_transcript(
        video_id=args.video_id,
        headless=not args.headed,
        cdp_url=args.cdp_url,
    )
    elapsed = time.time() - t0

    print(f"\n{'='*50}")
    print(f"Video: {result.video_id}")
    print(f"Method: {result.method}")
    print(f"Language: {result.language} ({'auto' if result.is_auto_generated else 'manual'})")
    print(f"Segments: {len(result.segments)}")
    print(f"Time: {elapsed:.2f}s")
    print(f"{'='*50}\n")

    for seg in result.segments[:3]:
        print(f"  [{seg.timestamp}] {seg.text[:50]}...")
    if len(result.segments) > 3:
        print(f"  ... +{len(result.segments) - 3} more")


if __name__ == "__main__":
    asyncio.run(main())
