# =============================================================================
# Leaf — minio (coelhonexus standalone, 20-data layer)
# =============================================================================
# MinIO standalone — foundational object storage.
#
# Consumed downstream by:
#   - postgresql (backup CronJob → MinIO backups bucket)
#   - loki / tempo / mimir (object backends for log/trace/metric storage)
#   - langfuse (clickhouse object storage, prompt artifacts)
#
# Adaptations vs COELHO Cloud's leaf:
#   - Drop the external-ingress-operator dependency (no operator in this cluster)
#   - External Ingresses (console + API) REMOVED from main.tf (2026-07-02) —
#     always inert on this cluster. Access MinIO via port-forward/NodePort.
#   - Credentials from env.hcl `demo` map instead of SOPS
# =============================================================================

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  # `//minio` (not a trailing path) tells Terragrunt to copy the WHOLE
  # infrastructure/modules/ tree into its cache, then cd into minio/ — needed
  # because main.tf's `module "k3d_expose_api"` / `"k3d_expose_console"`
  # reference a SIBLING module via a relative path (same fix as the other
  # 20-data leaves).
  source = "${get_repo_root()}/infrastructure/modules//minio"
}

dependency "k3d" {
  config_path = "../../00-bootstrap/k3d"

  mock_outputs = {
    cluster_name    = "mock"
    kubeconfig_path = "/tmp/nonexistent-kubeconfig"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# Ordering-only dep on monitoring-crds — minio module creates a ServiceMonitor.
dependencies {
  paths = ["../../10-platform/monitoring-crds"]
}

generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Auto-generated by Terragrunt. Do not edit.
    provider "kubernetes" {
      config_path = "${dependency.k3d.outputs.kubeconfig_path}"
    }

    provider "helm" {
      kubernetes = {
        config_path = "${dependency.k3d.outputs.kubeconfig_path}"
      }
    }
  EOF
}

inputs = {
  # ---------------------------------------------------------------------------
  # Credentials — from env.hcl `demo` map (NOT SOPS, demo-only scope).
  # ---------------------------------------------------------------------------
  root_user     = include.root.locals.env.demo.minio_access_key
  root_password = include.root.locals.env.demo.minio_secret_key

  # Defaults from variables.tf are appropriate for the standalone path:
  #   chart 5.4.0, standalone, 15Gi PVC, 10m/200Mi/384Mi resources,
  #   GOMEMLIMIT=350MiB. Default bucket = "backups" (inlined in
  #   helm/values.yaml.tpl).

  # Local access (k3d only) — API 30479->23015, Console 30480->23016, via
  # `k3d cluster edit coelhonexus --port-add "23015:30479@loadbalancer"`
  # `k3d cluster edit coelhonexus --port-add "23016:30480@loadbalancer"`
  # (run manually — not a Terraform resource, see infra/modules/k3d_expose).
  # NOTE: MinIO already has localhost access via standalone-port-forward.sh
  # (23008 console / 23009 API) — this is a second, redundant mechanism.
  enable_local_expose   = true
  k3d_api_node_port     = 30479
  k3d_console_node_port = 30480
}
