# =============================================================================
# Leaf — minio (coelhonexus standalone, 20-data layer)
# =============================================================================
# MinIO standalone — foundational object storage.
#
# Consumed downstream by:
#   - postgresql (backup CronJob → MinIO backups bucket)
#   - loki / tempo / mimir (object backends for log/trace/metric storage)
#   - langfuse (clickhouse object storage, prompt artifacts)
#
# Adaptations vs COELHO Cloud's leaf (otherwise verbatim):
#   - Drop dependency "tailscale_operator" (no operator in this cluster)
#   - Pass DUMMY tailscale_* inputs — the module's Ingress resources are
#     UNCONDITIONAL (verbatim rule = no module .tf edits). Created Ingresses
#     have no controller picking them up → they're inert API objects.
#     Harmless. Access MinIO via port-forward (host port 23005 → console).
#   - Credentials from env.hcl `demo` map instead of SOPS
# =============================================================================

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  source = "${get_repo_root()}/infrastructure/modules/minio"
}

dependency "k3d" {
  config_path = "../../00-bootstrap/k3d"

  mock_outputs = {
    cluster_name    = "mock"
    kubeconfig_path = "/tmp/nonexistent-kubeconfig"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
}

# Ordering-only dep on monitoring-crds — minio module creates a ServiceMonitor.
dependencies {
  paths = ["../../10-platform/monitoring-crds"]
}

generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Auto-generated by Terragrunt. Do not edit.
    provider "kubernetes" {
      config_path = "${dependency.k3d.outputs.kubeconfig_path}"
    }

    provider "helm" {
      kubernetes = {
        config_path = "${dependency.k3d.outputs.kubeconfig_path}"
      }
    }
  EOF
}

inputs = {
  # ---------------------------------------------------------------------------
  # Tailscale — DUMMY values. The module's Ingress resources are unconditional
  # (verbatim module = no .tf edits). With no tailscale-operator deployed,
  # these Ingress objects exist in the K8s API but have no controller, so they
  # never serve traffic. Harmless. Real access path is port-forward.
  # ---------------------------------------------------------------------------
  tailscale_hostname_console = "minio"
  tailscale_hostname_api     = "minio-api"
  tailscale_domain           = "tailscale.local"
  tailscale_ingress_class    = "tailscale"

  # ---------------------------------------------------------------------------
  # Credentials — from env.hcl `demo` map (NOT SOPS, demo-only scope).
  # ---------------------------------------------------------------------------
  root_user     = include.root.locals.env.demo.minio_access_key
  root_password = include.root.locals.env.demo.minio_secret_key

  # Defaults from variables.tf are appropriate for the standalone path:
  #   chart 5.4.0, standalone, 15Gi PVC, 10m/200Mi/384Mi resources,
  #   GOMEMLIMIT=350MiB. Default bucket = "backups" (inlined in
  #   helm/values.yaml.tpl).
}
